### ISSUE TITLE
client id link broken

### ISSUE THREAD

**Issue by adriancuadrado** [akeneo/api-php-client-ee#100]
![image](https://user-images.githubusercontent.com/29214635/124645259-83ef7800-de93-11eb-8f4e-648282cabbc7.png)

**Comment by Beatrix-droid** [comment]
May I take a look at this and try fixing it?

**Comment by adriancuadrado** [comment]
The broken link is in the README.md of the project: https://github.com/akeneo/api-php-client-ee#initialise-the-client

**Comment by LevFlavien** [comment]
HI @adriancuadrado,

Thank you for noticing this. As this EE repository is being deprecated, it has been fixed on the main one https://github.com/akeneo/api-php-client.

Regards,

Akeneo development team
