### ISSUE TITLE
Unable to install Akeneo API PHP Client Enterprise edition

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/api-php-client-ee#35]
Hi,
I'm using Akeneo enterprise edition. I try to install EE API PHP Client extension.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for akeneo/api-php-client-ee ^2.0 -> satisfiable by akeneo/api-php-client-ee[v2.0.0].
    - akeneo/api-php-client-ee v2.0.0 requires akeneo/api-php-client 2.0.x-dev@dev -> satisfiable by akeneo/api-php-client[2.0.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by redboxarnie** [comment]
put this into your root of composer.json: 
minimum-stability":"dev",

**Comment by ahocquard** [comment]
Hello, 

Actually, we did a mistake when releasing the client. It's based on the development branch of the CE client.
We will fix it as soon as possible.

Thanks for raising this issue.
I will let you know once it's done.

**Comment by LaurentPetard** [comment]
Hello,

We just release the version 2.0.1 that  solves this problem.

Thanks for raising this issue.

**Comment by Vanitha-bujjinga** [comment]
@ahocquard  / @LaurentPetard: Thank you for your response
