### ISSUE TITLE
Unable to retrieve a reference file by the download method

### ISSUE THREAD

**Issue by FabienSalles** [akeneo/api-php-client-ee#52]
Hello,

There is a method to download a reference file but I don't understand how to use it for my purpose. The method only return a stream content without any other information and we can't use just a content file to really download it :
```
$response = $this->httpClient->sendRequest('GET', $uri, ['Accept' => '*/*']);
return $response->getBody();
````

So we have to retrieve in a different way the mime type, the extension and create a new file name in order to download the file whereas these information are accessible directly in the Response object. 

Why not just return this object ?

**Comment by ahocquard** [comment]
Hello and thanks for raising this issue.

You're right. I think we designed it like the media file, but it is a mistake.
We should return the whole response for convenience.

I will think about how to handle it in a BC way.
We will probably add a method `downloadResponseFromLocalizableAsset`.

Regards,
Alexandre

**Comment by ahocquard** [comment]
Hello,

It has been improved in 4.0. The Response object is returned instead of the body as you suggested.
I close this issue as it is resolved, feel free to re-open it if you have a problem.
