### ISSUE TITLE
ReferenceEntityMediaFileApi cannot recognise code in response

### ISSUE THREAD

**Issue by annapivniak** [akeneo/api-php-client-ee#86]
Hi All, 

The method _ReferenceEntityMediaFileApi::extractCodeFromCreationResponse_ checks the incorrect header key here:
`https://github.com/akeneo/api-php-client-ee/blob/1577caa4ee0f94749d331cc6a225250620cd568c/src/Api/ReferenceEntityMediaFileApi.php#L76`
Instead of the `$headers['Reference-entities-media-file-code'] `it should be `$headers['Reference-Entities-Media-File-Code']`

Without this fix it is impossible to create a media file for the reference entity. Could you please adjust it? 

Thank you.

**Comment by ahocquard** [comment]
Hello,

When we create an asset on PIM side, here is the code:

```
        $headers = [
            'Reference-entities-media-file-code' => $fileInfo->getKey(),
            'Location' => $downloadMediaFileUrl
        ];

        return Response::create('', Response::HTTP_CREATED, $headers);
```

Are you sure the issue is here? Did you check directly with Postman or Curl the returned headers instead of using the PHP client?

**Comment by patrickzzz** [comment]
Hey,
@ahocquard: The problem occurs also on akeneo cloud 4 serenity (or only on serenity?).
@mmetayer: You linked #95 which is about the asset manager api. This one is about Reference Entity Media API. Also check screenshot in  #97 
Thanks!

**Comment by mmetayer** [comment]
@patrickzzz you're right, I mixed up the 2 APIs :/
The fix should be pretty similar though, I'll try to  open a PR as soon as I can (hopefully today)

**Comment by mmetayer** [comment]
@patrickzzz @annapivniak hopefully it should be fixed now, sorry again for the mixup
