### ISSUE TITLE
Missing line in AkeneoPimEnterpriseClient.php

### ISSUE THREAD

**Issue by Doodoune** [akeneo/api-php-client-ee#92]
In master, a partner noticed an error (internal ref SDS-14209)
```

Type error: Argument 13 passed to Akeneo\Pim\ApiClient\AkeneoPimClient::__construct() must be an instance of Akeneo\Pim\ApiClie
nt\Api\MeasurementFamilyApiInterface, instance of Akeneo\Pim\ApiClient\Api\AssociationTypeApi given, called in /var/www/symfony
/vendor/akeneo/api-php-client-ee/src/AkeneoPimEnterpriseClient.php on line 155
```
**Fixed by adding a missing line:**

What’s actually missing in https://github.com/akeneo/api-php-client-ee/blob/master/src/AkeneoPimEnterpriseClient.php
between line 152 and 153:
$measureFamilyApi,
$associationTypeApi,

is 'MeasurementFamilyApiInterface $measurementFamilyApi' like in https://github.com/akeneo/api-php-client/blob/master/src/AkeneoPimClient.php (line 92)

Could you please add it in master?

**Comment by LevFlavien** [comment]
Hi @Doodoune 

Since the EE package is getting deprecated and this issue is 2 years old, I'm closing this.
If this is still relevant to you, feel free to reopen an issue on the appropriate repository https://github.com/akeneo/api-php-client
