### ISSUE TITLE
Media upload fails on akeneo 4 while ReferenceEntityMediaFileApi.php prevents successful media upload

### ISSUE THREAD

**Issue by patrickzzz** [akeneo/api-php-client-ee#97]
Hey people,

the following bug appears on akeneo 4 (using **akeneo 4 cloud serenity**):

When using ReferenceEntityMediaFileApi to upload media,
`$imageCode = $client->getReferenceEntityMediaFileApi()->create($pathToLocalFile);`

you'll get a:

`Fatal error: Uncaught Akeneo\Pim\ApiClient\Exception\RuntimeException: The response does not contain the code of the created media-file. in /Users/myaccount/Development/project-dir/akeneo-api/vendor/akeneo/api-php-client-ee/src/Api/ReferenceEntityMediaFileApi.php:77
`

This is due to a incorrect (case sensitive) Header Reference. Using the correct header, everything works fine.

It expects: `Reference-entities-media-file-code`
Server returns: `Reference-Entities-Media-File-Code`

Please also see attached screenshot, to get a quicker understanding of the problem.

<img width="1147" alt="Bildschirmfoto 2020-10-09 um 10 12 34" src="https://user-images.githubusercontent.com/1732300/95559818-a5acf300-0a18-11eb-84ef-d5214699a4bf.png">

**Comment by patrickzzz** [comment]
Hey,
i just saw, this issue clones: #86

Although, the other issue was marked as being a clone of another problem (regarding assets) - but that's not the case.

**Comment by mmetayer** [comment]
Fixed by #98
